export const FETCH_EVENT = "FETCH_EVENT";
export const FETCH_EVENT_FAIL = "FETCH_EVENT_FAIL";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const UPLOAD_EVENT = "UPLOAD_EVENT";
export const UPLOAD_EVENT_FAIL = "UPLOAD_EVENT_FAIL";
export const UPLOAD_EVENT_SUCCESS = "UPLOAD_EVENT_SUCCESS";
