export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";
export const MODIFY_PROFILE = "MODIFY_PROFILE";
export const MODIFY_PROFILE_SUCCESS = "MODIFY_PROFILE_SUCCESS";
export const MODIFY_PROFILE_FAIL = "MODIFY_PROFILE_FAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const MODIFY_BALANCE = "MODIFY_BALANCE";
