export const FETCH_TICKET = "FETCH_TICKET";
export const FETCH_TICKET_SUCCESS = "FETCH_TICKET_SUCCESS";
export const FETCH_TICKET_FAIL = "FETCH_TICKET_FAIL";
export const BUY_TICKET_FAIL = "BUY_TICKET_FAIL";
